${LDAP_SCHEMA_INCLUDES}

modulepath  /usr/lib/openldap
moduleload  back_mdb
moduleload  argon2
moduleload  ppolicy
${LDAP_MODULE_LOADS}

pidfile     /run/openldap/slapd.pid
argsfile    /run/openldap/slapd.args

TLSCertificateFile    /config/tls/tls.crt
TLSCertificateKeyFile /config/tls/tls.key
TLSCACertificateFile  /config/tls/ca.crt
TLSProtocolMin        3.3
TLSCipherSuite        HIGH:!NULL:!MD5:!RC4:!ADH

password-hash {ARGON2}

${LDAP_SECURITY_CONFIG}
database    mdb
maxsize     1073741824
suffix      "${LDAP_SUFFIX}"
rootdn      "${LDAP_ROOT_DN}"
rootpw      ${LDAP_ROOT_PASSWORD}
directory   /config/data

index       objectClass     eq

overlay     ppolicy
ppolicy_hash_cleartext

${LDAP_OVERLAY_CONFIG}
