include     /etc/openldap/schema/core.schema
include     /etc/openldap/schema/cosine.schema
include     /etc/openldap/schema/inetorgperson.schema
include     /etc/openldap/schema/nis.schema

modulepath  /usr/lib/openldap
moduleload  back_mdb
moduleload  ppolicy
moduleload  argon2

pidfile     /run/openldap/slapd.pid
argsfile    /run/openldap/slapd.args

TLSCertificateFile    /config/tls/tls.crt
TLSCertificateKeyFile /config/tls/tls.key
TLSCACertificateFile  /config/tls/ca.crt

password-hash {ARGON2}

database    mdb
maxsize     1073741824
suffix      "${LDAP_SUFFIX}"
rootdn      "${LDAP_ROOT_DN}"
rootpw      ${LDAP_ROOT_PASSWORD}
directory   /config/data

index       objectClass eq
index       uid         eq
index       cn          eq
index       uniqueMember eq

access to attrs=userPassword
    by anonymous auth
    by self write
    by * none

access to *
    by self write
    by users read
    by * none

overlay     ppolicy
ppolicy_hash_cleartext
ppolicy_default "${LDAP_PPOLICY_DEFAULT_DN}"
